version: "3.9"
   
services:
  dev-db:
    image: postgres
    ports: 
        - "5432:5432"
    environment:
        - POSTGRES_DB=operational
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  unit-db:
    image: postgres
    ports: 
        - "5434:5432"
    environment:
        - POSTGRES_DB=operational
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres