version: "3.9"
   
services:
  app:
    build: .
    restart: on-failure
    ports:
        - "8000:8000"
    environment:
        DB_CONNECTION: "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}"
        DB_HOST: "${DB_HOST}"
    depends_on:
        - db
  db:
    image: postgres
    ports: 
        - "5432:5432"
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}